cf:
  butlers:
    #- pws: cf-butler-interesting-eagle.cfapps.io
  sslValidationSkipped: false

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

spring:
  codec:
    max-in-memory-size: 512000000
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

---
spring:
  profiles: cloud

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
